# Generated by Django 5.0.6 on 2024-06-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_management', '0001_initial'),
        ('patient_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('patient', 'name')},
        ),
    ]
